stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
    - echo "Compile complete."
  after_script:
    - bash src/telegram_bot.sh
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

clang-test-job:
  stage: style
  script:
    - echo "Linting code... This will take about 10 seconds."
    - cd src
    - clang-format -style=Google -n -Werror cat/*.c cat/*.h
    - clang-format -style=Google -n -Werror grep/*.c grep/*.h
    - echo "No lint issues found."
  after_script:
    - bash src/telegram_bot.sh
  allow_failure: false

unit-test-job:
  stage: test
  script:
    - cd src/cat
    - bash test_func_cat.sh
    - cd ../grep
    - bash test_func_grep.sh
  after_script:
    - bash src/telegram_bot.sh
  allow_failure: false

deploy-job:
  stage: deploy
  script:
    - bash src/deploy.sh
  after_script:
    - bash src/telegram_bot.sh
  allow_failure: false
  when: manual